<?php

$sql =<<<EOF
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_adv` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `weid` int(11) NOT NULL,
  `quan_id` int(11) NOT NULL,
  `mid` int(11) NOT NULL,
  `from_user` varchar(50) NOT NULL DEFAULT '',
  `openid` varchar(50) NOT NULL DEFAULT '',
  `nickname` varchar(50) NOT NULL DEFAULT '',
  `headimgurl` varchar(300) NOT NULL DEFAULT '',
  `total_amount` decimal(10,2) NOT NULL,
  `total_num` int(11) NOT NULL,
  `fee` decimal(10,2) NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` text,
  `images` text,
  `link` varchar(255) DEFAULT NULL,
  `telphone` varchar(20) DEFAULT NULL,
  `publish_time` int(11) DEFAULT NULL,
  `hot_time` int(11) NOT NULL DEFAULT '0',
  `top_level` int(11) NOT NULL DEFAULT '0',
  `rob_start_time` int(11) DEFAULT '0',
  `total_pay` decimal(10,2) DEFAULT NULL,
  `pay` decimal(10,2) DEFAULT NULL,
  `logid` int(11) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `rob_status` tinyint(1) NOT NULL DEFAULT '0',
  `views` int(11) NOT NULL DEFAULT '0',
  `links` int(11) NOT NULL DEFAULT '0',
  `rob_plan` mediumtext NOT NULL,
  `rob_amount` decimal(10,2) DEFAULT '0.00',
  `rob_users` int(11) NOT NULL DEFAULT '0',
  `rob_end_time` int(11) DEFAULT '0',
  `create_time` int(11) NOT NULL,
  `del` tinyint(1) DEFAULT '0',
  `op` tinyint(1) DEFAULT NULL,
  `op_remark` text,
  `op_admin` int(11) DEFAULT NULL,
  `kouling` varchar(255) NOT NULL,
  `is_open` int(1) DEFAULT '0',
  `is_pl` int(1) DEFAULT '0',
  `is_message` int(1) DEFAULT '0',
  `is_kouling` int(1) DEFAULT '0',
  `is_up` int(1) DEFAULT '0',
  `model` tinyint(1) DEFAULT '1',
  `group_size` smallint(6) DEFAULT NULL,
  `type` int(2) NOT NULL DEFAULT '1',
  `qr_code` varchar(250) DEFAULT NULL,
  `time_limit` int(1) DEFAULT '0',
  `time_limit_start` varchar(50) DEFAULT NULL,
  `time_limit_end` varchar(50) DEFAULT NULL,
  `job_submission_time` int(10) DEFAULT '0',
  `allocation_way` int(1) DEFAULT '0',
  `hx_status` tinyint(1) DEFAULT '0',
  `hx_pass` varchar(255) DEFAULT NULL,
  `wx_cardid` varchar(255) DEFAULT NULL,
  `share_url` varchar(255) DEFAULT '',
  `task_submit_switch` int(1) DEFAULT '0',
  `share_desc` varchar(255) DEFAULT '',
  `message_send` tinyint(1) NOT NULL DEFAULT '0',
  `wechat_sn` varchar(300) NOT NULL DEFAULT '',
  `addr_forward` int(1) DEFAULT '0',
  `addr_forward_url` varchar(255) DEFAULT '',
  `city` varchar(255) DEFAULT '',
  `fl_type` tinyint(1) DEFAULT '0',
  `summary` text,
  `couponc_images` text NOT NULL,
  `couponc_rule` text NOT NULL,
  `couponc_detail` varchar(255) NOT NULL DEFAULT '',
  `couponc_miaosha` varchar(255) NOT NULL DEFAULT '',
  `couponc_tel` varchar(255) NOT NULL DEFAULT '',
  `couponc_add` varchar(500) NOT NULL DEFAULT '',
  `couponc_shoper` varchar(255) NOT NULL DEFAULT '',
  `couponc_gift` varchar(255) NOT NULL DEFAULT '',
  `couponc_money` int(11) NOT NULL DEFAULT '0',
  `couponc_discount` int(11) NOT NULL DEFAULT '0',
  `company_name` varchar(255) NOT NULL DEFAULT '',
  `couponc_type` tinyint(1) NOT NULL,
  `couponc_name` varchar(255) NOT NULL,
  `hx_pwd` varchar(255) NOT NULL,
  `couponc_valid_date` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  KEY `cgc_ad_adv_key1` (`weid`,`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_banner` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `weid` int(10) NOT NULL,
  `quan_id` int(10) NOT NULL,
  `title` varchar(255) NOT NULL,
  `thumb` varchar(255) NOT NULL,
  `content` text,
  `displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `enabled` tinyint(1) DEFAULT '0',
  `url` varchar(255) NOT NULL,
  `status` tinyint(1) DEFAULT '1',
  `createtime` int(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_couponc` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `weid` int(11) NOT NULL,
  `quan_id` int(11) NOT NULL,
  `advid` int(11) NOT NULL,
  `mid` int(11) NOT NULL,
  `openid` varchar(50) NOT NULL DEFAULT '',
  `nickname` varchar(255) NOT NULL DEFAULT '',
  `avatar` varchar(255) NOT NULL DEFAULT '',
  `company_name` varchar(255) NOT NULL DEFAULT '',
  `couponc_type` tinyint(1) NOT NULL DEFAULT '0',
  `couponc_name` varchar(255) NOT NULL DEFAULT '',
  `couponc_valid_date` int(11) NOT NULL DEFAULT '0',
  `couponc_discount` int(11) NOT NULL DEFAULT '0',
  `couponc_money` int(11) NOT NULL DEFAULT '0',
  `couponc_gift` varchar(255) NOT NULL DEFAULT '',
  `couponc_shoper` varchar(255) NOT NULL DEFAULT '',
  `couponc_add` varchar(500) NOT NULL DEFAULT '',
  `couponc_tel` varchar(255) NOT NULL DEFAULT '',
  `couponc_detail` varchar(255) NOT NULL DEFAULT '',
  `couponc_rule` text NOT NULL,
  `couponc_images` text NOT NULL,
  `create_time` int(11) NOT NULL,
  `update_time` int(11) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `status_time` int(11) NOT NULL,
  `couponc_miaosha` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_group` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `weid` int(11) NOT NULL,
  `quan_id` int(11) NOT NULL,
  `advid` int(11) NOT NULL,
  `captain_id` int(11) NOT NULL,
  `captain_nickname` varchar(80) NOT NULL,
  `mine_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `nickname` varchar(80) DEFAULT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `headimgurl` varchar(255) DEFAULT NULL,
  `create_time` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_help` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `weid` int(11) NOT NULL,
  `quan_id` int(11) NOT NULL,
  `mid` int(11) NOT NULL,
  `helper_id` int(11) NOT NULL,
  `create_time` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_member` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `weid` int(10) NOT NULL,
  `quan_id` int(11) NOT NULL,
  `uid` int(10) NOT NULL,
  `from_user` varchar(50) NOT NULL DEFAULT '',
  `openid` varchar(50) NOT NULL DEFAULT '',
  `nickname` varchar(50) NOT NULL DEFAULT '',
  `headimgurl` varchar(250) NOT NULL DEFAULT '',
  `thumb` varchar(255) NOT NULL,
  `nicheng` varchar(255) NOT NULL,
  `status` int(2) NOT NULL,
  `credit` decimal(10,2) DEFAULT '0.00',
  `fabu` decimal(10,2) DEFAULT '0.00',
  `rob` decimal(10,2) DEFAULT '0.00',
  `up_money` decimal(10,2) NOT NULL DEFAULT '0.00',
  `follow` tinyint(1) DEFAULT '0',
  `follow_time` int(10) DEFAULT '0',
  `type` int(2) NOT NULL,
  `last_city` varchar(255) NOT NULL,
  `createtime` int(10) NOT NULL,
  `rob_next_time` int(10) NOT NULL DEFAULT '0',
  `fstatus` int(1) DEFAULT '0',
  `is_revice` int(1) DEFAULT '0',
  `inviter_id` int(10) DEFAULT '0',
  `qr_code` varchar(250) DEFAULT NULL,
  `telphone` varchar(20) DEFAULT NULL,
  `message_notify` int(1) NOT NULL DEFAULT '0',
  `ori_openid` varchar(255) DEFAULT '',
  `no_account_amount` decimal(10,2) DEFAULT '0.00',
  `fee` decimal(10,2) DEFAULT '0.00',
  `qrcode_imge` varchar(500) DEFAULT NULL,
  `qrcode_poster` varchar(500) DEFAULT NULL,
  `poster_time` int(11) DEFAULT NULL,
  `vip_id` varchar(20) DEFAULT NULL,
  `vip_name` varchar(20) DEFAULT NULL,
  `vip_recharge` decimal(10,2) DEFAULT '0.00',
  `vip_rob` decimal(10,2) DEFAULT '0.00',
  `credit1` decimal(10,2) DEFAULT NULL,
  `credit2` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cgc_ad_member_key1` (`weid`,`quan_id`,`openid`),
  KEY `cgc_ad_member_key2` (`weid`,`quan_id`,`id`),
  KEY `cgc_ad_member_key3` (`weid`,`quan_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_message` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `weid` int(11) DEFAULT NULL,
  `advid` int(11) DEFAULT NULL,
  `mid` int(11) DEFAULT NULL,
  `upbdate` varchar(244) DEFAULT NULL,
  `content` varchar(255) DEFAULT NULL,
  `status` int(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_paylog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `weid` int(11) DEFAULT NULL,
  `mid` int(11) DEFAULT NULL,
  `quan_id` int(11) DEFAULT NULL,
  `advid` int(11) DEFAULT NULL,
  `total_amount` float(244,2) DEFAULT NULL,
  `upbdate` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_poster` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `weid` int(11) DEFAULT '0',
  `quan_id` int(11) NOT NULL,
  `quan_name` varchar(255) NOT NULL,
  `bg` varchar(255) DEFAULT '',
  `data` text,
  `keyword` varchar(255) DEFAULT '',
  `createtime` int(11) DEFAULT '0',
  `waittext` varchar(255) DEFAULT '',
  `oktext` varchar(255) DEFAULT '',
  `subtext` varchar(255) DEFAULT '',
  `templateid` varchar(255) DEFAULT '',
  `entrytext` varchar(255) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_uniacid` (`weid`),
  KEY `idx_createtime` (`createtime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_pv` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `weid` int(10) NOT NULL,
  `quan_id` int(10) NOT NULL,
  `mid` int(10) NOT NULL,
  `advid` int(10) NOT NULL,
  `createtime` int(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_quan` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `weid` int(11) NOT NULL,
  `aname` varchar(255) NOT NULL,
  `notice` text,
  `rule` text,
  `begin_time` tinyint(2) NOT NULL,
  `over_time` tinyint(2) NOT NULL,
  `cold_time` smallint(6) NOT NULL,
  `total_min` decimal(10,2) DEFAULT NULL,
  `total_max` decimal(10,2) DEFAULT NULL,
  `avg_min` decimal(10,2) DEFAULT NULL,
  `percent` decimal(10,2) DEFAULT NULL,
  `tx_min` decimal(10,2) DEFAULT NULL,
  `top_line` decimal(10,2) DEFAULT NULL,
  `follow_logo` varchar(255) NOT NULL,
  `follow_url` text,
  `sharetitle` varchar(255) NOT NULL,
  `sharedesc` varchar(255) NOT NULL,
  `sharelogo` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `status` tinyint(1) NOT NULL,
  `shenhe` tinyint(1) DEFAULT '0',
  `del` tinyint(1) DEFAULT '0',
  `is_message` int(1) DEFAULT '1',
  `is_follow` int(1) DEFAULT '0',
  `create_time` int(11) NOT NULL,
  `update_time` int(11) NOT NULL,
  `last_city` varchar(255) NOT NULL,
  `is_pl` int(1) DEFAULT '0',
  `piece_model` varchar(255) DEFAULT NULL,
  `groupmax` smallint(6) NOT NULL,
  `total_min2` decimal(10,2) NOT NULL,
  `total_max2` decimal(10,2) NOT NULL,
  `avg_min2` decimal(10,2) NOT NULL,
  `up_rob_fee` decimal(10,2) NOT NULL,
  `up_send_fee` decimal(10,2) NOT NULL,
  `total_min4` decimal(10,2) DEFAULT NULL,
  `total_max4` decimal(10,2) DEFAULT NULL,
  `avg_min4` decimal(10,2) DEFAULT NULL,
  `tx_follow` int(1) NOT NULL DEFAULT '0',
  `pp_mode` int(1) DEFAULT '0',
  `pp_openid` text,
  `task_submit_switch` tinyint(1) DEFAULT '0',
  `group_guanzhu` tinyint(1) DEFAULT '0',
  `hx_switch` tinyint(1) DEFAULT '0',
  `views` int(10) DEFAULT '0',
  `yun_fkz` tinyint(1) DEFAULT '0',
  `yun_rule` text,
  `guanzhu_qrcode` varchar(255) NOT NULL DEFAULT '',
  `guanzhu_name` varchar(50) NOT NULL DEFAULT '',
  `guanzhu_direct` tinyint(1) DEFAULT '0',
  `task_guanzhu` tinyint(1) DEFAULT '0',
  `kf_openid` text,
  `guanzhu_note` text,
  `guanzhu_key` varchar(255) DEFAULT '',
  `total_min5` decimal(10,2) DEFAULT NULL,
  `total_max5` decimal(10,2) DEFAULT NULL,
  `avg_min5` decimal(10,2) DEFAULT NULL,
  `tx_control` int(1) DEFAULT '0',
  `tx_num` int(1) DEFAULT '0',
  `tx_money` int(11) DEFAULT '0',
  `total_min6` decimal(10,2) DEFAULT NULL,
  `total_max6` decimal(10,2) DEFAULT NULL,
  `avg_min6` decimal(10,2) DEFAULT NULL,
  `total_min7` decimal(10,2) DEFAULT NULL,
  `total_max7` decimal(10,2) DEFAULT NULL,
  `avg_min7` decimal(10,2) DEFAULT NULL,
  `addr_forward` int(1) DEFAULT '0',
  `tx_percent` int(3) DEFAULT '0',
  `hx_show` int(1) DEFAULT '0',
  `menu_name` varchar(30) DEFAULT '',
  `menu_url` varchar(255) DEFAULT '',
  `regular_user_momeny` int(11) DEFAULT '0',
  `click_multiple` int(11) DEFAULT '0',
  `vip_valid` int(1) DEFAULT '0',
  `addr_forward_url` varchar(255) DEFAULT '',
  `forbidden_addr` varchar(100) DEFAULT '',
  `piece_model_authority` varchar(30) DEFAULT '',
  `message_notify` tinyint(1) NOT NULL DEFAULT '0',
  `total_min8` decimal(10,2) DEFAULT NULL,
  `total_max8` decimal(10,2) DEFAULT NULL,
  `avg_min8` decimal(10,2) DEFAULT NULL,
  `is_page_follow` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_red` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `weid` int(11) NOT NULL,
  `quan_id` int(11) NOT NULL,
  `advid` int(11) NOT NULL,
  `mid` int(11) NOT NULL,
  `money` decimal(10,2) DEFAULT NULL,
  `up_money` decimal(10,2) DEFAULT NULL,
  `total_money` decimal(10,2) DEFAULT NULL,
  `is_luck` int(11) DEFAULT NULL,
  `is_shit` int(11) DEFAULT NULL,
  `create_time` int(11) NOT NULL,
  `status` int(1) NOT NULL DEFAULT '0',
  `hx_status` tinyint(1) DEFAULT '0',
  `wx_code` varchar(32) DEFAULT NULL,
  `share_app_message_count` int(5) DEFAULT '0',
  `share_time_line_count` int(5) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  KEY `cgc_ad_red_key1` (`weid`,`quan_id`,`advid`,`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_rule` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `weid` int(10) NOT NULL,
  `ruleid` int(10) NOT NULL,
  `quan_id` int(10) NOT NULL,
  `news_title` varchar(255) NOT NULL,
  `news_thumb` varchar(255) NOT NULL,
  `news_content` varchar(255) NOT NULL,
  `createtime` int(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_setting` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `weid` int(10) NOT NULL,
  `appid` varchar(255) NOT NULL,
  `secret` varchar(32) NOT NULL,
  `mchid` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `ip` varchar(255) NOT NULL,
  `qn_ak` varchar(255) NOT NULL,
  `qn_sk` varchar(255) NOT NULL,
  `qn_bucket` varchar(255) NOT NULL,
  `qn_api` varchar(255) NOT NULL,
  `bd_ak` varchar(255) NOT NULL,
  `pay_type` int(1) NOT NULL DEFAULT '0',
  `yunpay_no` varchar(255) DEFAULT NULL,
  `yunpay_pid` varchar(255) DEFAULT NULL,
  `yunpay_key` varchar(255) DEFAULT NULL,
  `is_qniu` int(1) DEFAULT '0',
  `is_type` int(1) DEFAULT '0',
  `template_id` text NOT NULL,
  `tuisong` text,
  `kf_openid` text,
  `qq` text,
  `rush_text` varchar(20) NOT NULL,
  `unit_text` varchar(20) NOT NULL,
  `task_template_id` varchar(200) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_task` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `weid` int(11) NOT NULL,
  `quan_id` int(11) NOT NULL,
  `advid` int(11) NOT NULL,
  `mid` int(11) NOT NULL,
  `nickname` varchar(80) DEFAULT NULL,
  `headimgurl` varchar(255) DEFAULT NULL,
  `status` tinyint(4) DEFAULT '0',
  `create_time` int(11) NOT NULL,
  `money` decimal(10,2) NOT NULL DEFAULT '0.00',
  `content` text,
  `task_status` int(1) DEFAULT '0',
  `images` text,
  `openid` varchar(50) DEFAULT '',
  `hx_status` tinyint(1) DEFAULT '0',
  `share_app_message_count` int(5) DEFAULT '0',
  `share_time_line_count` int(5) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_tx` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `weid` int(11) NOT NULL,
  `quan_id` int(11) NOT NULL,
  `mid` int(11) NOT NULL,
  `openid` varchar(100) NOT NULL,
  `money` decimal(10,2) DEFAULT NULL,
  `money_before` decimal(10,2) DEFAULT NULL,
  `money_after` decimal(10,2) DEFAULT NULL,
  `status` tinyint(1) NOT NULL,
  `channel` tinyint(1) DEFAULT NULL,
  `mch_billno` varchar(50) DEFAULT NULL,
  `out_billno` varchar(50) DEFAULT NULL,
  `out_money` int(11) DEFAULT NULL,
  `tag` text,
  `remark` text,
  `create_time` int(11) NOT NULL,
  `update_time` int(11) NOT NULL,
  `tx_status` tinyint(1) NOT NULL DEFAULT '0',
  `nickname` varchar(100) NOT NULL DEFAULT '',
  `headimgurl` varchar(300) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_vip_pay` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quan_id` int(11) NOT NULL,
  `weid` int(11) DEFAULT NULL,
  `mid` int(11) DEFAULT NULL,
  `openid` varchar(50) NOT NULL DEFAULT '',
  `nickname` varchar(50) NOT NULL DEFAULT '',
  `headimgurl` varchar(300) NOT NULL DEFAULT '',
  `vip_id` int(11) DEFAULT NULL,
  `vip_name` varchar(20) DEFAULT NULL,
  `vip_recharge` decimal(10,2) DEFAULT NULL,
  `pay` decimal(10,2) DEFAULT NULL,
  `status` int(1) DEFAULT '0',
  `createtime` int(11) DEFAULT NULL,
  `wechat_sn` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_vip_rule` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quan_id` int(11) NOT NULL,
  `weid` int(11) DEFAULT NULL,
  `vip_name` varchar(20) DEFAULT NULL,
  `vip_recharge` decimal(10,2) DEFAULT NULL,
  `vip_rob` decimal(10,2) DEFAULT NULL,
  `piece_model` varchar(255) DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `createtime` int(11) NOT NULL DEFAULT '0',
  `is_spill` int(2) NOT NULL DEFAULT '0',
  `spill_prompt` varchar(100) NOT NULL DEFAULT '',
  `spill_fee` decimal(10,2) NOT NULL DEFAULT '0.00',
  `spill_number` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_ad_yure` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `weid` int(10) NOT NULL,
  `quan_id` int(10) NOT NULL,
  `fee` decimal(10,2) DEFAULT NULL,
  `time` int(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_addr_group` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `weid` int(10) NOT NULL,
  `addr` varchar(200) NOT NULL,
  `group_id` int(50) NOT NULL DEFAULT '0',
  `group_name` varchar(50) NOT NULL DEFAULT '分组名称',
  `url` varchar(300) NOT NULL,
  `remark` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_share_member` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(3) NOT NULL,
  `headimgurl` varchar(200) NOT NULL COMMENT '头像',
  `openid` varchar(100) NOT NULL COMMENT '微信id',
  `nickname` varchar(200) NOT NULL COMMENT '昵称',
  `realname` varchar(30) NOT NULL COMMENT '真实姓名',
  `sex` int(1) NOT NULL COMMENT '性别',
  `city` varchar(20) NOT NULL COMMENT '城市',
  `province` varchar(10) NOT NULL COMMENT '省份',
  `subscribe` int(1) NOT NULL COMMENT '是否关注',
  `total_money` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT '总金额',
  `w_money` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT '未提现金额',
  `y_money` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT '已提现金额',
  `cz_money` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT '充值金额',
  `zf_money` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT '支付金额',
  `status` int(1) NOT NULL DEFAULT '0' COMMENT '状态 0正常，1拉黑',
  `vip_status` int(1) NOT NULL DEFAULT '0' COMMENT 'vip状态 0否，1是',
  `start_createtime` int(10) NOT NULL DEFAULT '0' COMMENT 'vip开始时间',
  `end_createtime` int(10) NOT NULL DEFAULT '0' COMMENT 'vip结束时间',
  `createtime` int(10) DEFAULT NULL,
  `lh_no` int(2) NOT NULL DEFAULT '0' COMMENT '拉黑次数',
  PRIMARY KEY (`id`),
  KEY `cgc_share_member1` (`uniacid`,`openid`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_share_record` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(3) NOT NULL,
  `url_id` int(5) NOT NULL COMMENT '链接id',
  `openid` varchar(100) NOT NULL COMMENT '微信id',
  `ip` varchar(200) NOT NULL COMMENT 'ip地址',
  `createtime` int(10) DEFAULT NULL,
  `share_openid` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `cgc_share_record_index` (`uniacid`,`url_id`,`openid`),
  KEY `cgc_share_record_gindex1` (`uniacid`,`createtime`,`url_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_share_url` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(3) NOT NULL,
  `title` varchar(300) NOT NULL DEFAULT '' COMMENT '标题',
  `content` text NOT NULL COMMENT '内容',
  `openid` varchar(100) NOT NULL DEFAULT '',
  `nickname` varchar(50) NOT NULL DEFAULT '',
  `url` varchar(300) NOT NULL DEFAULT '' COMMENT '微信链接地址或者头条地址',
  `money` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT '设置金额',
  `num` int(4) NOT NULL DEFAULT '0' COMMENT '份数',
  `y_num` int(4) NOT NULL DEFAULT '0' COMMENT '已领取份数',
  `share_type` int(1) NOT NULL DEFAULT '0' COMMENT '0全部，1朋友圈，2朋友微信群',
  `sx_bl` int(4) NOT NULL DEFAULT '0' COMMENT '手续费',
  `sex` int(1) NOT NULL DEFAULT '0' COMMENT '性别 0 全部，男 1，女2',
  `province` varchar(200) NOT NULL DEFAULT '' COMMENT '省份',
  `city` varchar(200) NOT NULL DEFAULT '' COMMENT '城市',
  `pay_status` int(1) NOT NULL DEFAULT '0' COMMENT '付款状态 0,未付款1,已付款',
  `wechat_sn` varchar(200) DEFAULT NULL COMMENT '微信单号',
  `order_sn` varchar(200) DEFAULT NULL COMMENT '订单号',
  `createtime` int(10) DEFAULT NULL,
  `desc` varchar(100) NOT NULL DEFAULT '',
  `pic` varchar(500) NOT NULL DEFAULT '',
  `zf_money` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT '支付金额',
  `tk_money` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT '退款金额',
  `tk_status` int(1) NOT NULL DEFAULT '0' COMMENT '退款状态',
  `paytype` varchar(20) DEFAULT '' COMMENT '付款方式',
  `pay_log` varchar(200) DEFAULT '' COMMENT '支付日志',
  `dj` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT '单价',
  `read_num` int(10) DEFAULT '0' COMMENT '阅读数',
  `import_url_type` int(1) NOT NULL DEFAULT '0' COMMENT '链接类型 0 微信链接.1 其他链接',
  `read_single_money` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT '阅读单价',
  `read_money` int(5) NOT NULL DEFAULT '0' COMMENT '阅读总金额',
  PRIMARY KEY (`id`),
  KEY `cgc_share_url_gindex1` (`uniacid`,`id`),
  KEY `cgc_share_url_gindex2` (`uniacid`,`openid`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_share_user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(3) NOT NULL,
  `url_id` int(5) NOT NULL COMMENT '链接id',
  `headimgurl` varchar(200) NOT NULL COMMENT '头像',
  `openid` varchar(100) NOT NULL COMMENT '微信id',
  `nickname` varchar(200) NOT NULL COMMENT '昵称',
  `realname` varchar(30) NOT NULL COMMENT '真实姓名',
  `sex` int(1) NOT NULL COMMENT '性别',
  `city` varchar(20) NOT NULL COMMENT '城市',
  `province` varchar(10) NOT NULL COMMENT '省份',
  `subscribe` int(1) NOT NULL COMMENT '是否关注',
  `share_status` int(1) NOT NULL DEFAULT '0' COMMENT '分享状态 0未分享，1已分享',
  `status` int(1) NOT NULL DEFAULT '0' COMMENT '状态 0正常,1拉黑',
  `money` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT '红包金额',
  `createtime` int(10) DEFAULT NULL,
  `read_num` int(10) NOT NULL DEFAULT '0',
  `url` varchar(500) NOT NULL DEFAULT '',
  `title` varchar(500) NOT NULL DEFAULT '',
  `paytype` varchar(20) DEFAULT '' COMMENT '付款方式',
  `share_openid` varchar(50) NOT NULL DEFAULT '',
  `hb_status` int(1) NOT NULL DEFAULT '0' COMMENT '状态 0 已发送,1发送失败',
  `district` varchar(500) NOT NULL DEFAULT '',
  `share_type` int(1) NOT NULL DEFAULT '0' COMMENT '0全部，1朋友圈，2朋友微信群',
  PRIMARY KEY (`id`),
  KEY `cgc_share_user_index1` (`uniacid`,`url_id`,`openid`),
  KEY `cgc_share_user_gindex1` (`uniacid`,`url_id`),
  KEY `cgc_share_user_gindex2` (`uniacid`,`share_openid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_share_vip` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(3) NOT NULL,
  `openid` varchar(100) NOT NULL DEFAULT '',
  `nickname` varchar(50) NOT NULL DEFAULT '',
  `zf_money` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT '支付金额',
  `paytype` varchar(20) DEFAULT '' COMMENT '付款方式',
  `pay_log` varchar(200) DEFAULT '' COMMENT '支付日志',
  `order_sn` varchar(20) DEFAULT '' COMMENT '订单号',
  `wechat_sn` varchar(30) DEFAULT '' COMMENT '微信订单号',
  `status` int(1) DEFAULT '0' COMMENT '支付状态',
  `createtime` int(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
EOF;
pdo_run($sql);
