<?php

$sql =<<<EOF
CREATE TABLE IF NOT EXISTS `ims_haoman_updatehb_addad` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) NOT NULL DEFAULT '0',
  `rulename` varchar(255) NOT NULL COMMENT '活动规则',
  `adlogo` varchar(255) NOT NULL DEFAULT '0' COMMENT '广告图片',
  `adtitle` varchar(255) NOT NULL DEFAULT '0' COMMENT '广告标题',
  `addetails` varchar(255) NOT NULL DEFAULT '0' COMMENT '广告简介',
  `adlink` varchar(255) NOT NULL DEFAULT '0' COMMENT '广告链接',
  `createtime` int(11) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0表示未投放，1表示投放',
  PRIMARY KEY (`id`),
  KEY `idx_id_rulename` (`id`,`rulename`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_haoman_updatehb_award` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `weid` int(10) NOT NULL,
  `rid` int(10) unsigned NOT NULL COMMENT '规则ID',
  `from_user` varchar(50) DEFAULT '0' COMMENT '用户ID',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '微信头像',
  `credit` int(10) NOT NULL,
  `prizetype` varchar(10) DEFAULT '' COMMENT '类型，0表示刷新红包，1表示转发得红包，2表示口令得红包，3表示扫码得红包',
  `status` tinyint(1) DEFAULT '0' COMMENT '1标示未提现，2标示已经提现，3标示被拒绝',
  `createtime` int(10) DEFAULT '0',
  `title` varchar(50) NOT NULL COMMENT '奖项',
  `total` int(11) NOT NULL COMMENT '数量',
  `probalilty` varchar(5) NOT NULL COMMENT '概率',
  `description` varchar(100) NOT NULL DEFAULT '' COMMENT '描述',
  `card_id` varchar(255) NOT NULL,
  `fansID` int(11) DEFAULT '0',
  `jifen` int(10) NOT NULL COMMENT '获得的积分',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '联系电话',
  `iszhuangyuan` tinyint(1) NOT NULL DEFAULT '0',
  `titleid` int(10) NOT NULL,
  `awardname` varchar(50) DEFAULT '' COMMENT '描述',
  `awardsimg` varchar(200) NOT NULL COMMENT '奖品图片',
  `prize` int(11) DEFAULT '0' COMMENT '奖品ID',
  `consumetime` int(10) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_from_user` (`from_user`),
  KEY `indx_createtime` (`createtime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_haoman_updatehb_baoming` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
  `uniacid` int(10) unsigned NOT NULL COMMENT '公众号ID',
  `from_user` varchar(50) NOT NULL DEFAULT '' COMMENT '用户openid',
  `realname` varchar(20) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '联系电话',
  `address` varchar(255) NOT NULL DEFAULT '' COMMENT '联系地址',
  `createtime` int(10) DEFAULT '0',
  `status` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_from_user` (`from_user`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_haoman_updatehb_cardticket` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `weid` int(10) DEFAULT NULL,
  `createtime` varchar(20) DEFAULT NULL,
  `ticket` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_haoman_updatehb_cash` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `rid` int(11) DEFAULT '0',
  `fansID` int(11) DEFAULT '0',
  `from_user` varchar(50) DEFAULT '0' COMMENT '用户ID',
  `avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '微信头像',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '联系电话',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `awardname` varchar(50) DEFAULT '' COMMENT '兑奖金额',
  `prizetype` varchar(10) DEFAULT '' COMMENT '类型',
  `awardsimg` varchar(200) NOT NULL COMMENT '奖品图片',
  `prize` int(11) DEFAULT '0' COMMENT '奖品ID',
  `credit` int(11) DEFAULT '0' COMMENT '奖品金额',
  `createtime` int(10) DEFAULT '0',
  `consumetime` int(10) DEFAULT '0',
  `status` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_haoman_updatehb_data` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
  `uniacid` int(10) unsigned NOT NULL COMMENT '公众号ID',
  `from_user` varchar(50) NOT NULL DEFAULT '' COMMENT '用户openid',
  `fromuser` varchar(50) NOT NULL DEFAULT '' COMMENT '分享人openid',
  `avatar` varchar(512) NOT NULL DEFAULT '' COMMENT '微信头像',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `visitorsip` varchar(15) NOT NULL DEFAULT '' COMMENT '访问IP',
  `visitorstime` int(10) unsigned NOT NULL COMMENT '访问时间',
  `viewnum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '查看次数',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_from_user` (`from_user`),
  KEY `indx_fromuser` (`fromuser`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_haoman_updatehb_fans` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `rid` int(11) DEFAULT '0',
  `uniacid` int(11) DEFAULT '0',
  `fansID` int(11) DEFAULT '0',
  `from_user` varchar(50) DEFAULT '' COMMENT '用户ID',
  `avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '微信头像',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `realname` varchar(20) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '联系电话',
  `address` varchar(255) NOT NULL DEFAULT '' COMMENT '联系地址',
  `hb_total` int(11) DEFAULT '0' COMMENT '刷新红包总金额',
  `share_total` int(11) DEFAULT '0' COMMENT '分享得红包总金额',
  `pw_total` int(11) DEFAULT '0' COMMENT '口令得红包总金额',
  `scan_total` int(11) DEFAULT '0' COMMENT '扫码得红包总金额',
  `isad` tinyint(1) DEFAULT '0' COMMENT '是否看过场景',
  `iscode` tinyint(1) DEFAULT '0' COMMENT '是否短信验证过',
  `istx_code` tinyint(1) DEFAULT '0' COMMENT '是否提现验证过',
  `isshare` tinyint(1) DEFAULT '0' COMMENT '是否分享过',
  `bbm_use_times` int(11) DEFAULT '0',
  `num` int(11) DEFAULT '0' COMMENT '短信验证次数',
  `totalnum` int(11) DEFAULT '0' COMMENT '已经提现金额',
  `createtime` int(10) DEFAULT '0',
  `status` tinyint(1) DEFAULT '0',
  `today_most_times` int(11) DEFAULT '0' COMMENT '每日最多次数',
  `sharenum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '分享量',
  `sharetime` int(10) DEFAULT '0' COMMENT '提现次数',
  `awardingid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '兑奖地址ID',
  `todaynum` int(11) DEFAULT '0',
  `is_closebg` int(11) DEFAULT '0' COMMENT '是否关闭背景音乐',
  `is_hbok` int(11) DEFAULT '0',
  `zy_times` int(11) DEFAULT '0',
  `xx_zy_times` int(11) DEFAULT '0',
  `daynum` int(11) DEFAULT '0',
  `jifen` int(10) NOT NULL COMMENT '总积分',
  `awardnum` int(11) DEFAULT '0',
  `last_time` int(10) DEFAULT '0',
  `zhongjiang` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_from_user` (`from_user`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_mobile` (`mobile`),
  KEY `indx_jifen` (`jifen`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_haoman_updatehb_hb` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) unsigned NOT NULL DEFAULT '0',
  `set` text,
  `mchid` varchar(100) NOT NULL DEFAULT '' COMMENT '商户号',
  `password` varchar(2550) NOT NULL DEFAULT '' COMMENT '商户密码',
  `appid` varchar(100) NOT NULL DEFAULT '' COMMENT '服务号ID',
  `secret` varchar(255) NOT NULL DEFAULT '' COMMENT '服务号secret',
  `ip` varchar(100) NOT NULL DEFAULT '' COMMENT '服务器IP',
  `sname` varchar(100) NOT NULL DEFAULT '' COMMENT '公众号名称',
  `wishing` varchar(100) NOT NULL DEFAULT '' COMMENT '祝福语',
  `actname` varchar(100) NOT NULL DEFAULT '' COMMENT '红包活动名称',
  `logo` varchar(255) NOT NULL DEFAULT '' COMMENT 'logo',
  `hbwishing` varchar(100) DEFAULT '' COMMENT '红包祝福语',
  `hbactname` varchar(100) DEFAULT '' COMMENT '红包活动',
  `hbremark` varchar(150) DEFAULT '' COMMENT '红包描述',
  `createtime` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_haoman_updatehb_jiequan` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `appid` varchar(255) DEFAULT '',
  `appsecret` varchar(255) DEFAULT '',
  `appid_share` varchar(255) DEFAULT '',
  `appsecret_share` varchar(255) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_haoman_updatehb_password` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
  `uniacid` int(10) unsigned NOT NULL COMMENT '公众号ID',
  `from_user` varchar(50) NOT NULL DEFAULT '' COMMENT '用户openid',
  `pwid` varchar(50) NOT NULL DEFAULT '' COMMENT '口令ID',
  `avatar` varchar(512) NOT NULL DEFAULT '' COMMENT '微信头像',
  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `visitorsip` varchar(15) NOT NULL DEFAULT '' COMMENT '访问IP',
  `visitorstime` int(10) unsigned NOT NULL COMMENT '访问时间',
  `viewnum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '状态',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_haoman_updatehb_pici` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT '0',
  `rid` int(11) DEFAULT '0',
  `pici` varchar(10) DEFAULT '' COMMENT '批次',
  `rulename` varchar(50) DEFAULT NULL COMMENT '适用规则名称',
  `codenum` int(11) DEFAULT '0' COMMENT '口令数量',
  `is_qrcode` int(11) DEFAULT '0' COMMENT '是否生成二维码',
  `is_qrcode2` int(11) DEFAULT '0' COMMENT '是否生成永久二维码',
  `createtime` int(10) DEFAULT '0',
  `status` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`),
  KEY `indx_pici` (`pici`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_haoman_updatehb_prize` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(10) NOT NULL,
  `rid` int(10) unsigned NOT NULL COMMENT '规则ID',
  `line1` int(10) NOT NULL COMMENT '所在区间1',
  `line2` int(10) NOT NULL COMMENT '所在区间2',
  `credit` int(10) NOT NULL COMMENT '增长区间1',
  `credit2` int(10) NOT NULL COMMENT '增长区间2',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_haoman_updatehb_pw` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `uniacid` int(10) DEFAULT NULL,
  `rid` int(10) unsigned NOT NULL COMMENT '规则ID',
  `pici` varchar(10) NOT NULL COMMENT '批次',
  `pwid` varchar(50) NOT NULL DEFAULT '' COMMENT '口令标示符',
  `title` varchar(35) DEFAULT NULL COMMENT '口令',
  `rulename` varchar(50) DEFAULT NULL COMMENT '适用规则名称',
  `iscqr` int(11) DEFAULT '0' COMMENT '是否生成二维码',
  `starttime` int(10) DEFAULT '0',
  `endtime` int(10) DEFAULT '0',
  `num` int(10) DEFAULT '0',
  `status` tinyint(1) DEFAULT '0',
  `createtime` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `indx_rid` (`rid`),
  KEY `indx_pwid` (`pwid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_haoman_updatehb_reply` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned DEFAULT '0',
  `uniacid` int(11) DEFAULT '0',
  `title` varchar(50) DEFAULT '',
  `picture` varchar(100) NOT NULL COMMENT '活动图片',
  `description` varchar(255) DEFAULT '',
  `starttime` int(10) DEFAULT '0',
  `endtime` int(10) DEFAULT '0',
  `rules` text NOT NULL COMMENT '规则',
  `gl_openid` varchar(300) DEFAULT '',
  `timenum` int(10) DEFAULT '0',
  `up_qrcode` varchar(255) DEFAULT '',
  `share_url` varchar(300) DEFAULT '',
  `share_gz` varchar(300) DEFAULT '',
  `share_type` tinyint(1) DEFAULT '0',
  `is_hbad` tinyint(1) DEFAULT '0',
  `hbtotal_top` int(11) DEFAULT '0',
  `hbtotal_top_dec` varchar(300) DEFAULT '',
  `is_sharetype` tinyint(1) DEFAULT '0' COMMENT '分享后赠送次数方式',
  `share_title` varchar(200) DEFAULT '',
  `share_desc` varchar(300) DEFAULT '',
  `share_imgurl` varchar(255) NOT NULL COMMENT '分享朋友或朋友圈图',
  `getip` tinyint(1) DEFAULT '0',
  `getip_addr` text NOT NULL COMMENT '限制地区ip',
  `noip_url` varchar(300) DEFAULT '',
  `allowip` text NOT NULL,
  `isallowip` tinyint(2) DEFAULT '0',
  `is_openbbm` tinyint(1) DEFAULT '0',
  `bbm_use_times` int(11) DEFAULT '0',
  `share_acid` int(10) DEFAULT '0',
  `tx_most` int(11) DEFAULT '0',
  `xf_condition` tinyint(1) DEFAULT '0',
  `number_times` int(11) DEFAULT '0',
  `share_topnum` int(11) DEFAULT '0' COMMENT '预留，分享朋友点击进来的上限预留',
  `share_credit` int(11) DEFAULT '0' COMMENT '预留，分享朋友或朋友圈点击进来的积分',
  `isshow` tinyint(1) DEFAULT '0',
  `isonce` tinyint(1) DEFAULT '0',
  `isonline` tinyint(1) DEFAULT '0',
  `copyright` varchar(20) DEFAULT '',
  `createtime` int(10) DEFAULT '0',
  `isappkey` tinyint(2) DEFAULT '0',
  `bd_key` varchar(50) DEFAULT '',
  `address_sf` text NOT NULL,
  `address_sq` text NOT NULL,
  `address_qx` text NOT NULL,
  `tx_code` tinyint(2) DEFAULT '0',
  `switch` tinyint(2) DEFAULT '0',
  `teladdr` tinyint(2) DEFAULT '0',
  `tellimit` int(10) DEFAULT '0',
  `appkey` varchar(200) DEFAULT '0',
  `secretKey` varchar(200) DEFAULT '0',
  `sign` varchar(200) DEFAULT '0',
  `sms_id` varchar(200) DEFAULT '0',
  `outtips` varchar(200) DEFAULT '0',
  `viewnum` int(11) DEFAULT '0' COMMENT '浏览次数',
  `fansnum` int(11) DEFAULT '0' COMMENT '参与人数',
  `scene` tinyint(1) DEFAULT '0',
  `out_scene_url` varchar(255) NOT NULL COMMENT '外链场景URL',
  `p1_bg` varchar(255) NOT NULL COMMENT '自带场景背景图',
  `p1_top` varchar(255) NOT NULL COMMENT '自带场景顶部图',
  `p1_bottom` varchar(255) NOT NULL COMMENT '自带场景底部图',
  `p2_bg` varchar(255) NOT NULL COMMENT '自带场景背景图',
  `p2_top` varchar(255) NOT NULL COMMENT '自带场景顶部图',
  `p2_bottom` varchar(255) NOT NULL COMMENT '自带场景底部图',
  `p3_bg` varchar(255) NOT NULL COMMENT '自带场景背景图',
  `p3_top` varchar(255) NOT NULL COMMENT '自带场景顶部图',
  `p3_isphone` tinyint(1) DEFAULT '0',
  `p3_phone` varchar(50) DEFAULT '0',
  `start_bg` varchar(250) DEFAULT '',
  `start_top` varchar(250) DEFAULT '',
  `start_dec` varchar(80) DEFAULT '',
  `start_music` varchar(250) DEFAULT '',
  `hb_time` int(11) DEFAULT '0',
  `hb_credit1` int(11) DEFAULT '0',
  `hb_credit2` int(11) DEFAULT '0',
  `hbtype` tinyint(1) DEFAULT '0',
  `hbtx_time` int(10) DEFAULT '0',
  `hb_local` tinyint(1) DEFAULT '0',
  `hb_localcredit1` int(11) DEFAULT '0',
  `hb_localcredit2` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
EOF;
pdo_run($sql);
