<?php

$sql = "
CREATE TABLE IF NOT EXISTS `ims_uber_dazitu_fans` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(10) unsigned DEFAULT '0',
  `rid` int(10) unsigned DEFAULT '0',
  `mchid` int(10) unsigned NOT NULL DEFAULT '0',
  `openid` varchar(100) DEFAULT '' COMMENT '用户ID',
  `oauthopenid` varchar(100) DEFAULT '' COMMENT '授权用户ID',
  `uid` int(10) unsigned DEFAULT '0',
  `nickname` varchar(100) DEFAULT '',
  `avatar` varchar(250) DEFAULT '',
  `realname` varchar(100) DEFAULT '',
  `mobile` varchar(30) DEFAULT '' COMMENT '登记信息(手机等)',
  `address` varchar(250) NOT NULL DEFAULT '',
  `email` varchar(100) NOT NULL DEFAULT '',
  `qq` varchar(20) NOT NULL DEFAULT '',
  `credit` decimal(10,2) DEFAULT '0.00' COMMENT '单次最高分数',
  `totalcredit` decimal(10,2) DEFAULT '0.00' COMMENT '累计分数',
  `totalnum` int(11) DEFAULT '0' COMMENT '总次数',
  `todaynum` int(11) DEFAULT '0' COMMENT '今天次数',
  `createtime` int(10) unsigned DEFAULT '0' COMMENT '最后游戏时间',
  `sharenum` int(11) DEFAULT '0' COMMENT '总分享次数',
  `shareawardnum` int(11) DEFAULT '0' COMMENT '分享抽奖次数',
  `todaysharenum` int(11) DEFAULT '0' COMMENT '今日分享次数',
  `lastsharetime` int(10) DEFAULT '0',
  `pubdate` int(10) unsigned DEFAULT '0',
  `redeemcode` varchar(20) NOT NULL DEFAULT '0',
  `ip` varchar(16) NOT NULL DEFAULT '0',
  `status` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `exchange` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `rid` (`rid`),
  KEY `mchid` (`mchid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_uber_dazitu_reply` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(10) unsigned NOT NULL DEFAULT '0',
  `uniacid` int(10) unsigned NOT NULL DEFAULT '0',
  `title` varchar(100) NOT NULL,
  `starttime` int(10) DEFAULT '0',
  `endtime` int(10) DEFAULT '0',
  `ruletext` text,
  `playtimes` smallint(6) unsigned DEFAULT '0',
  `everydaytimes` smallint(6) unsigned NOT NULL DEFAULT '0',
  `isfollow` tinyint(1) unsigned DEFAULT '0',
  `awardtext` text,
  `followurl` varchar(200) DEFAULT '',
  `copyright` varchar(250) NOT NULL,
  `shownum` tinyint(1) unsigned DEFAULT '0',
  `viewnum` int(10) unsigned NOT NULL DEFAULT '0',
  `isprofile` tinyint(1) DEFAULT '0',
  `profile` varchar(250) DEFAULT '',
  `exchange` tinyint(1) unsigned DEFAULT '0',
  `share_title` varchar(200) DEFAULT '',
  `share_image` varchar(100) DEFAULT '',
  `share_url` varchar(100) NOT NULL DEFAULT '',
  `share_desc` varchar(250) DEFAULT '',
  `createtime` int(10) DEFAULT '0',
  `adimgurl` varchar(100) NOT NULL DEFAULT '',
  `adurl` varchar(100) NOT NULL DEFAULT '',
  `bgurl` varchar(100) DEFAULT '',
  `coverurl` varchar(100) DEFAULT '',
  `prize` text NOT NULL,
  `status` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `daysharenum` int(10) unsigned NOT NULL DEFAULT '0',
  `shareawardnum` int(10) unsigned NOT NULL DEFAULT '0',
  `gametime` int(10) unsigned NOT NULL DEFAULT '15',
  `gamelevel` int(10) unsigned NOT NULL DEFAULT '3',
  `mode` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `showusernum` int(10) unsigned NOT NULL DEFAULT '200',
  `qrcode` varchar(100) NOT NULL DEFAULT '',
  `qrcodetext` varchar(100) DEFAULT '',
  `bgmusic` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `rid` (`rid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS  `ims_uber_dazitu_share` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(10) unsigned NOT NULL,
  `rid` int(10) unsigned NOT NULL,
  `share_openid` varchar(100) NOT NULL,
  `share_time` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `rid` (`rid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
";
pdo_query($sql);
