<?php
//decode by QQ:3213288469 http://www.zheyitianshi.com/
defined('IN_IA') or exit('Access Denied'); function https_request($url, $data = null) { $curl = curl_init(); curl_setopt($curl, CURLOPT_URL, $url); curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, FALSE); curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, FALSE); if (!empty($data)) { curl_setopt($curl, CURLOPT_POST, 1); curl_setopt($curl, CURLOPT_POSTFIELDS, $data); } curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1); $output = curl_exec($curl); curl_close($curl); return $output; } function httpGet($url) { $curl = curl_init(); curl_setopt($curl, CURLOPT_RETURNTRANSFER, true); curl_setopt($curl, CURLOPT_TIMEOUT, 500); curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false); curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false); curl_setopt($curl, CURLOPT_URL, $url); $res = curl_exec($curl); curl_close($curl); return $res; } function getwuserinfo($openid, $returnaccess) { $access_token = $returnaccess; $url = "https://api.weixin.qq.com/cgi-bin/user/info?access_token=" . $access_token . "&openid=" . $openid . "&lang=zh_CN"; $wuser = https_request($url); $wuser = json_decode($wuser, true); return $wuser; } function getaccesstoken($appid, $appsecret) { $url = "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=".$appid."&secret=".$appsecret; $result = httpGet($url); $jsoninfo = json_decode($result, true); $access_token = $jsoninfo["access_token"]; return $access_token; } function findaccesstoken($appid, $appsecret) { $access_token = getaccesstoken($appid, $appsecret); if($access_token){ $returnaccess = $access_token; } else { $returnaccess = FALSE; } return $returnaccess; } function wxtostr($str){ Global $charset; if ($charset == 'gb2312') { $returnstr = iconv("gbk", 'utf-8', $str); }elseif ($charset == 'UTF-8') { $returnstr = $str; }elseif ($charset == 'big5') { $returnstr = iconv("big5", 'utf-8', $str); } return $returnstr; } function sendmsg($appid,$appsecret,$openid,$content){ $access_token = findaccesstoken($appid, $appsecret) ; $url = "https://api.weixin.qq.com/cgi-bin/message/custom/send?access_token=".$access_token; $json = '{
                "touser":"'.$openid.'",
                "msgtype":"text",
                "text":
                        {
                            "content":"'.urlencode($content).'"
                        },
            }'; $result = https_request($url,urldecode($json)); } function replace($word){ $first = str_replace("<p>", "", stripslashes($word)); $sercont = str_replace("</p>", "<br>", $first); return $sercont; } function savepic($post){ $picname = '/uploads/'.time().rand(100,999).'.jpeg'; $file='../addons/kuaiwei_xxcx'.$picname; $base64=base64_decode($post); $save = file_put_contents($file, $base64); if($save){ return $file; } } function savepic2($post){ $picname = '/uploads2/'.time().rand(100,999).'.jpeg'; $file='../addons/kuaiwei_xxcx'.$picname; $base64=base64_decode($post); $save = file_put_contents($file, $base64); if($save){ return $file; } } function tcupload($file,$xcid){ $ttk=new TTKClient(MY_ACCESSKEY,MY_SECRETKEY); $picurl = $file; $res=$ttk->uploadFile($xcid,$picurl); $res = str_replace("{", "", $res); $res = str_replace("}", "", $res); $res = str_replace('"', "", $res); $array = explode(',',$res); $s_url = str_replace('s_url:', "", $array[7]); if($s_url){ return stripslashes($s_url); }else{ return $file; } } function get_ip_data($ips){ $ip=file_get_contents("http://ip.taobao.com/service/getIpInfo.php?ip=".$ips); $ip = json_decode($ip, true); if($ip['code']){ return false; } $data = $ip['data']; return $data; } function export_csv($filename,$data) { header("Content-type:text/csv"); header("Content-Disposition:attachment;filename=".$filename); header('Cache-Control:must-revalidate,post-check=0,pre-check=0'); header('Expires:0'); header('Pragma:public'); echo u2g($data); } function u2g($str) { return iconv('utf-8','gb2312//IGNORE',$str); } function input_csv($handle) { $out = array (); $n = 0; while ($data = fgetcsv($handle, 100000)) { $num = count($data); for ($i = 0; $i < $num; $i++) { $out[$n][$i] = $data[$i]; } $n++; } return $out; } function replacestr($str) { $result = str_replace('=','',$str); $result = str_replace('"','',$result); $result = str_replace('\'','',$result); return $result; }